services:
  db:
    image: postgres:17.2
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  web:
    build: .
    command: "/bin/bash -c 'pip install -r requirements.txt; ./manage.py migrate; python manage.py runserver 0.0.0.0:8000'"
    volumes:
      - .:/src
    working_dir: /src
    ports:
        - "8000:8000"
    env_file:
      - .env

volumes:
  pgdata: