# Generated by Django 5.1.5 on 2025-10-19 12:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='project_tasks',
        ),
        migrations.AddField(
            model_name='projects',
            name='collaborators',
            field=models.ManyToManyField(related_name='project', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projects',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='projects',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Urgent', 'Urgent')], default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='projects',
            name='status',
            field=models.CharField(choices=[('Backlog', 'Backlog'), ('To do', 'To Do'), ('In progress', 'In Progress'), ('Done', 'Done')], default='Backlog', max_length=100),
        ),
        migrations.AddField(
            model_name='projects',
            name='task_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='projects',
            name='main_app',
            field=models.ManyToManyField(related_name='projects', to='main_app.tasksinfo'),
        ),
        migrations.AlterField(
            model_name='tasksinfo',
            name='assignee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tasksinfo',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='tasksinfo',
            name='task_description',
            field=models.TextField(null=True),
        ),
    ]
