# Generated by Django 5.1.5 on 2025-10-21 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_project_collaborators_alter_project_creator_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='main_app',
        ),
        migrations.AddField(
            model_name='project',
            name='tasks',
            field=models.ManyToManyField(related_name='projects', to='main_app.task'),
        ),
    ]
